BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefBaseOfSharingID_GNR_FixInfo
GO
ALTER TABLE GNR.FixInfo SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefCategoryID_GNR_DataSystem
GO
ALTER TABLE GNR.DataSystem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefDetailAccountID_GNR_DetailAccount
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefDetailAccount2ID_GNR_DetailAccount
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefDetailAccount3ID_GNR_DetailAccount
GO
ALTER TABLE GNR.DetailAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefLedgerAccountID_GNR_LedgerAccount
GO
ALTER TABLE GNR.LedgerAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor
	DROP CONSTRAINT FK_STO_ImportDetailIncrementalFactor_RefImportHeaderID_STO_ImportHeader
GO
ALTER TABLE STO.ImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailIncrementalFactor SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
