BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefWriterID_GNR_Users
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefEditorID_GNR_Users
GO
ALTER TABLE GNR.Users SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefDetailAccountID_GNR_DetailAccount
GO
ALTER TABLE GNR.DetailAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefWarehouseID_GNR_Warehouse
GO
ALTER TABLE GNR.Warehouse SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefVoucherHeaderID_ACC_VoucherHeader
GO
ALTER TABLE ACC.VoucherHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefFiscalYearID_GNR_FiscalYear
GO
ALTER TABLE GNR.FiscalYear SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefVoucherTypeID_GNR_FixInfo
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefKindID_GNR_FixInfo
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefStatusID_GNR_FixInfo
GO
ALTER TABLE STO.ReturnImportHeader
	DROP CONSTRAINT FK_STO_ReturnImportHeader_RefAmountConfirmStatusID_GNR_FixInfo
GO
ALTER TABLE GNR.FixInfo SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE STO.ReturnImportDetailTransport
	DROP CONSTRAINT FK_STO_ReturnImportDetailTransport_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE LIQ.RelatedSubSystemVoucher
	DROP CONSTRAINT FK_LIQ_RelatedSubSystemVoucher_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE STO.ReturnImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE LIQ.RelatedSubSystemVoucher SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailTransport SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
