BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailPaymentMethod
	DROP CONSTRAINT FK_STO_ImportDetailPaymentMethod_RefPaymentTypeID_GNR_FixInfo
GO
ALTER TABLE GNR.FixInfo SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailPaymentMethod
	DROP CONSTRAINT FK_STO_ImportDetailPaymentMethod_RefImportHeaderID_STO_ImportHeader
GO
ALTER TABLE STO.ImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailPaymentMethod SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
