BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailTransport
	DROP CONSTRAINT FK_STO_ImportDetailTransport_RefDetailAccountID_GNR_DetailAccount
GO
ALTER TABLE GNR.DetailAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailTransport
	DROP CONSTRAINT FK_STO_ImportDetailTransport_RefImportHeaderID_STO_ImportHeader
GO
ALTER TABLE STO.ImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ImportDetailTransport SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
