BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefBaseUnitID_GNR_Unit
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefLateralUnitID_GNR_Unit
GO
ALTER TABLE GNR.Unit SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefGoodsID_GNR_Goods
GO
ALTER TABLE GNR.Goods SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefImportDetailItemID_STO_ImportDetailItem
GO
ALTER TABLE STO.ImportDetailItem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailItem
	DROP CONSTRAINT FK_STO_ReturnImportDetailItem_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE STO.ReturnImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GNR.TrackDetailValue
	DROP CONSTRAINT FK_GNR_TrackDetailValue_RefReturnImportDetailItemID_STO_ReturnImportDetailItem
GO
ALTER TABLE STO.ReturnImportDetailItem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GNR.TrackDetailValue SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
