BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefDetailAccountID_GNR_DetailAccount
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefDetailAccount2ID_GNR_DetailAccount
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefDetailAccount3ID_GNR_DetailAccount
GO
ALTER TABLE GNR.DetailAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefLedgerAccountID_GNR_LedgerAccount
GO
ALTER TABLE GNR.LedgerAccount SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger
	DROP CONSTRAINT FK_STO_ReturnImportDetailOppositLedger_RefReturnImportHeaderID_STO_ReturnImportHeader
GO
ALTER TABLE STO.ReturnImportHeader SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE STO.ReturnImportDetailOppositLedger SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
